site_name: Maxine
site_description: Service registry, discovery, and operational control plane
repo_url: https://github.com/VrushankPatel/Maxine
repo_name: VrushankPatel/Maxine
nav:
  - Overview: index.md
  - Features: features.md
  - API: api.md
  - Helm: helm.md
  - Contributing: contributing.md
  - Roadmap: roadmap.md
  - Maintainer: about.md
  - License: licence.md
theme:
  name: readthedocs
  nav_style: dark
  highlightjs: true
plugins:
  - swagger-ui-tag:
      background: white
site_dir: buildocs
