name: maxine_client
description: Dart client SDK for Maxine service registry
version: 1.0.0
homepage: https://github.com/VrushankPatel/Maxine

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  http: ^1.0.0

dev_dependencies:
  test: ^1.17.0