image:
  repository: ghcr.io/vrushankpatel/maxine
  tag: "1.0.0"

auth:
  existingSecret: maxine-auth

persistence:
  enabled: true
  size: 5Gi
  storageClassName: standard

logs:
  persistence:
    enabled: true
    size: 5Gi
    storageClassName: standard

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: maxine.example.com
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi
