apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "maxine.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "maxine.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "maxine.name" . }}
    spec:
      containers:
      - name: maxine
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}