apiVersion: v1
kind: Service
metadata:
  name: {{ include "maxine.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "maxine.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "maxine.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}