apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceendpoints.maxine.io
spec:
  group: maxine.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                serviceName:
                  type: string
                endpoints:
                  type: array
                  items:
                    type: object
                    properties:
                      address:
                        type: string
                      port:
                        type: integer
                      weight:
                        type: integer
                        default: 1
                      metadata:
                        type: object
                        additionalProperties:
                          type: string
                      healthCheck:
                        type: object
                        properties:
                          path:
                            type: string
                            default: '/health'
                          interval:
                            type: string
                            default: '30s'
                          timeout:
                            type: string
                            default: '5s'
                          unhealthyThreshold:
                            type: integer
                            default: 3
                          healthyThreshold:
                            type: integer
                            default: 2
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum: ['Pending', 'Registering', 'Registered', 'Failed']
                registeredAt:
                  type: string
                endpointCount:
                  type: integer
                healthyEndpoints:
                  type: integer
                lastError:
                  type: string
  scope: Namespaced
  names:
    plural: serviceendpoints
    singular: serviceendpoint
    kind: ServiceEndpoint
    shortNames:
      - se
